// Chart ideas for the AI Infrastructure Financing case study.
// Appendix material, not report text. Research notes behind every row are in reviews/research-*.md.
const L = {
  pitchbookElPaso: "https://pitchbook.com/news/articles/investors-flock-to-12-5b-data-center-bond-deal-for-blackrock-sponsored-sopaipilla",
  ifrHyperion: "https://www.ifre.com/ifr-awards/2340435/the-metablue-owl-deal-broken-down-off-balance-sheet-gymnastics-24-years-after-enron",
  metaHyperion: "https://investor.atmeta.com/investor-news/press-release-details/2025/Meta-Announces-Joint-Venture-with-Funds-Managed-by-Blue-Owl-Capital-to-Develop-Hyperion-Data-Center/default.aspx",
  digitalDrive: "https://www.bloomberg.com/news/articles/2026-09-23/coreweave-tied-data-center-raises-1-1-billion-in-junk-bonds",
  hut8: "https://investingnews.com/hut-8-closes-4-25-billion-of-investment-grade-senior-secured-notes-for-beacon-point-data-center-project/",
  saline: "https://www.related.com/press-releases/2026-04-24/related-digital-announces-financing-16-billion-oracle-data-center-project",
  aligned: "https://www.globenewswire.com/news-release/2026/07/28/3334210/0/en/Aligned-Data-Centers-Completes-1-18-Billion-Securitization-Financing.html",
  apolloXai: "https://www.apollo.com/insights-news/pressreleases/2026/01/apollo-backs-5-4-billion-valor-and-xai-data-center-compute-infrastructure-transaction-with-3-5-billion-capital-solution-3214463",
  abilene: "https://www.costar.com/article/1387166843/first-stargate-data-center-project-lands-7-1-billion-construction-loan",
  kbraVlt10: "https://www.businesswire.com/news/home/20260603885897/en/KBRA-Assigns-Preliminary-Ratings-to-BX-2026-VLT10",
  cwDdtl3: "https://investors.coreweave.com/news/news-details/2025/CoreWeave-Closes-2-6-Billion-Secured-Debt-Financing-Facility-Strengthening-Market-Position-as-AI-Cloud-Leader/default.aspx",
  cwDdtl4: "https://investors.coreweave.com/news/news-details/2026/CoreWeave-Closes-Landmark-8-5-Billion-Financing-Facility-Achieving-First-Investment-Grade-Rated-GPU-backed-Financing/default.aspx",
  cwDdtl5: "https://www.businesswire.com/news/home/20260518337916/en/",
  cwDdtl55: "https://www.sec.gov/Archives/edgar/data/1769628/000176962826000357/ex991pr.htm",
  lambda: "https://lambda.ai/blog/lambda-prices-926-million-senior-secured-term-loan-b-facility",
  reutersIssuance: "https://www.investing.com/news/stock-market-news/hyperscaler-debt-binge-pushes-yields-up-as-investor-demand-cools-4820617",
  cnbcYields: "https://www.cnbc.com/2026/09/27/debt-hungry-data-center-companies-increased-risk-bond-yields-spike.html",
  oracleQ1: "https://s23.q4cdn.com/440135859/files/content_files/Q1-FY27-Oracle-Earnings-Slides.pdf",
  oracleFM: "https://www.bloomberg.com/news/articles/2026-09-24/oracle-cites-force-majeure-to-shield-itself-on-controversial-data-center",
  jupiterFT: "https://www.thestar.com.my/tech/tech-news/2026/09/19/oracle039s-18-billion-data-center-debt-under-pressure-ft-reports",
  moodysLeases: "https://fortune.com/2026/02/25/hyperscaler-risk-off-balance-sheet-662-billion-data-center-commitments-meta-amazon-microsoft-oracle-alphabet/",
  fredBBB: "https://fred.stlouisfed.org/series/BAMLC0A4CBBB",
};

const charts = [
  {
    id: "D",
    slot: "Page 5, left",
    title: "Leverage by Financing Route (%)",
    type: "Horizontal bar, maroon shades, highest leverage on top",
    rows: [
      ["Hut 8 Beacon Point bonds, loan to cost", "95", "Hut 8 and counsel via press"],
      ["Oracle Saline SPV bonds, loan to cost", "about 85 (derived from 15% equity)", "Related Digital and Blackstone releases"],
      ["Aligned data center ABS, loan to value", "70.0", "Aligned release, S&P presale"],
      ["xAI chip vehicle, advance on purchase", "about 65 (derived, $3.5bn of $5.4bn)", "Apollo release"],
      ["Stargate Abilene bank loans, loan to cost", "about 64 (derived, $9.6bn of about $15bn)", "Trade press"],
    ],
    note: "Three of five bars are derived. Keep the footnote that says so, or swap them for bars with a stated ratio (for example Vantage UK ABS at 53.6% LTV).",
    links: [
      ["Beacon Point 95% loan to cost", L.hut8],
      ["Saline financing", L.saline],
      ["Aligned ABS", L.aligned],
      ["Apollo and Valor xAI financing", L.apolloXai],
      ["Abilene construction loan", L.abilene],
      ["KBRA on BX 2026 VLT10 (108.4% KBRA LTV)", L.kbraVlt10],
    ],
  },
  {
    id: "B",
    slot: "Page 5, right",
    title: "Hyperscaler Bond Issuance ($bn)",
    type: "Column chart, estimate bars shaded lighter",
    rows: [
      ["2025 full year (Amazon, Alphabet, Meta, Oracle)", "about 108", "Reuters and LSEG"],
      ["2026 to date (same four issuers)", "about 223", "LSEG via CNBC"],
      ["2026 estimate (five hyperscalers)", "about 250", "Goldman Sachs via Reuters"],
      ["2027 estimate (five hyperscalers)", "about 400", "Goldman Sachs via Reuters"],
    ],
    note: "The to date figure runs through late August. Morgan Stanley reported no hyperscaler USD IG deals in September, but only through an aggregator. Refresh with an LSEG pull before publishing.",
    links: [
      ["Reuters analysis of LSEG data", L.reutersIssuance],
      ["CNBC on data center bond yields", L.cnbcYields],
    ],
  },
  {
    id: "C",
    slot: "Page 7, left",
    title: "Project Bond Yields by Tenant (%)",
    type: "Horizontal bar, tenant and pricing month in each label",
    rows: [
      ["Hut 8 Beacon Point, AA- or better tenant", "6.129 (T+165), Jun 2026", "Hut 8 via press"],
      ["Meta Hyperion, A+", "6.581 (T+225), Oct 2025", "IFR"],
      ["Meta El Paso, A+", "7.534 (T+287.5), Jul 2026", "PitchBook"],
      ["Digital Drive, CoreWeave tenant, BB-", "9.25 yield at 98.5, Sep 2026", "Bloomberg"],
    ],
    note: "Pricing dates differ, so the spreads are the cleaner comparison. Digital Drive has no Treasury spread on record, only about 270bps over similarly rated debt.",
    links: [
      ["El Paso pricing", L.pitchbookElPaso],
      ["Hyperion structure and pricing", L.ifrHyperion],
      ["Digital Drive notes", L.digitalDrive],
      ["Beacon Point notes", L.hut8],
    ],
  },
  {
    id: "A",
    slot: "Page 7, right",
    title: "GPU Loan Spreads (bps over SOFR)",
    type: "Horizontal bar, counterparty and rating in each label",
    rows: [
      ["CoreWeave DDTL 4.0, Meta contract, A3", "225", "CoreWeave release"],
      ["Lambda term loan B, IG offtaker, Baa2", "300", "Lambda release"],
      ["CoreWeave DDTL 3.0, OpenAI contract", "400", "CoreWeave release"],
      ["CoreWeave DDTL 5.0, Ba2 and BB+", "450", "CoreWeave release"],
      ["CoreWeave DDTL 5.5, Ba2 and BB+", "550", "CoreWeave 8-K exhibit"],
    ],
    note: "DDTL 4.0's SOFR plus 225 appears in the company release per the research notes, but one research pass rated it aggregator only. Confirm in the release before verifying.",
    links: [
      ["DDTL 3.0", L.cwDdtl3],
      ["DDTL 4.0", L.cwDdtl4],
      ["DDTL 5.0", L.cwDdtl5],
      ["DDTL 5.5", L.cwDdtl55],
      ["Lambda TLB", L.lambda],
    ],
  },
  {
    id: "E",
    slot: "Optional, page 7 swap",
    title: "Oracle Project Jupiter Timeline",
    type: "Simple dated timeline",
    rows: [
      ["Late 2025", "About $18bn construction loan from about 20 banks", "Bloomberg"],
      ["Jul 9, 2026", "S&P cuts Oracle to BBB-", "S&P via press"],
      ["Sep 10, 2026", "Q1 FY27, RPO $664bn, FCF negative $5.4bn", "Oracle"],
      ["Mid Sep 2026", "Loan quoted at 89 to 91 cents", "FT"],
      ["Sep 24, 2026", "Force majeure notice to the Blue Owl developer", "Bloomberg"],
      ["Feb 1, 2027", "Gas pipeline in service date", "Bloomberg"],
    ],
    note: "Useful if the Oracle section needs a visual in place of chart C.",
    links: [
      ["Oracle Q1 FY27 slides", L.oracleQ1],
      ["Force majeure notice", L.oracleFM],
      ["FT on loan prices", L.jupiterFT],
    ],
  },
  {
    id: "F",
    slot: "Optional",
    title: "Off Balance Sheet Lease Commitments",
    type: "Single bar or stat callout",
    rows: [
      ["Not yet commenced hyperscaler data center leases", "$662bn", "Moody's via Fortune"],
      ["As a share of adjusted debt", "113%", "Moody's via Fortune"],
    ],
    note: "Pairs with the S&P versus Moody's divergence on page 5.",
    links: [["Moody's lease analysis", L.moodysLeases], ["BBB spread, FRED", L.fredBBB]],
  },
];

module.exports = { charts, L };
